name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: abtinm/qmapping:ci
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: submodule
        run: | 
             git config --global --add safe.directory '*'
             git submodule update --init --recursive
      - name: build openwbo
        run: make r
        working-directory: lib/Open-WBO-Inc/
      - name: test
        run: python3 src/satmap.py examples/jku_constraint_based/3_17_13.qasm --arch tokyo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
